
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "debian-12-bookworm-amd64"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          sudo chown -R 1001 $(pwd)

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w . && make update
          if [[ -n "$DOCKER_USERNAME" ]]; then
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && echo "logged_in=true" >> $GITHUB_OUTPUT
          fi
          make build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
