
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.target }} + ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - "latest"
        image:
          - "ubuntu-22.04-jammy-arm64v8"
          - "ubuntu-22.04-jammy-ppc64le"
        include:
          - image: "ubuntu-22.04-jammy-arm64v8"
            qemu-arch: "aarch64"
          - image: "ubuntu-22.04-jammy-ppc64le"
            qemu-arch: "ppc64le"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        if: "matrix.qemu-arch"
        run: |
          docker run --rm --privileged aptman/qus -s -- -p ${{ matrix.qemu-arch }}

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          if [ "${{ matrix.target }}" = "latest" ]; then
            git submodule update --remote Pillow
            (cd Pillow && git checkout main)
          fi
          sudo chown -R 1000 $(pwd)

      - name: Test Image Build
        if: "matrix.test-image"
        run: |
          cd "${{ matrix.test-image }}"
          make pull || (sudo chmod a+w . && make update && make build BRANCH=main)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w . && make update
          if [[ -n "$DOCKER_USERNAME" ]]; then
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && echo "logged_in=true" >> $GITHUB_OUTPUT
          fi
          make build BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test image
        run: |
          cd "${{ matrix.image }}"
          make test BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Log image size
        run: |
          docker images

      - name: Push image
        if: "steps.build.outputs.logged_in == 'true'
                           && github.event_name == 'push'
                           && github.ref == 'refs/heads/main'
                           && matrix.target == 'latest'"
        run: make push-${{ matrix.image }} BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Post build
        if: always()
        run: sudo chown -R $(id -u) $(pwd)

  success:
    needs: build
    runs-on: ubuntu-latest
    name: Build successful
    steps:
      - name: Success
        run: echo Build Successful
