
name: Docker images

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        image:
          - "amazon-2023-amd64"
          - "ubuntu-22.04-jammy-amd64"
          - "ubuntu-24.04-noble-amd64"

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: true

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          if [[ -n "$matrix.test-image" ]]; then
            git submodule update --remote --init --recursive Pillow
          else
            git submodule update --remote Pillow
          fi
          (cd Pillow && git checkout main)
          sudo chown -R 1001 "$(pwd)"

      - name: Test Image Build
        if: "matrix.test-image"
        run: |
          cd "${{ matrix.test-image }}"
          make pull || (sudo chmod a+w . && make update && make build BRANCH=main)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ARGS: ${{ matrix.docker-args }}

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w . && make update
          if [[ -n "$DOCKER_USERNAME" ]]; then
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && echo "logged_in=true" >> "$GITHUB_OUTPUT"
          fi
          make build BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ARGS: ${{ matrix.docker-args }}
