
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ubuntu-25.04-amd64"
          - "ubuntu-25.04-amd64-stdgnu23"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          sudo chown -R 1001 $(pwd)

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w . && docker pull ubuntu:plucky
          docker build .
