name: Docker images

on: [push]

jobs:
  build:
    name: arch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          sudo chown -R 1001 $(pwd)

      - name: Build image
        id: build
        run: |
          cd arch && sudo chmod a+w . && docker pull greyltc/archlinux
          docker build .
