
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.target }} + ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - "latest"
        image:
          - "fuzz"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          if [ "${{ matrix.target }}" = "latest" ]; then
            git submodule update --remote Pillow
            (cd Pillow && git checkout main)
          fi
          sudo chown -R 1000 $(pwd)

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w .
          if [[ -n "$DOCKER_USERNAME" ]]; then
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && echo "::set-output name=logged_in::true"
          fi
          make build BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
