
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "Sane"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Build image
        id: build
        run: |
          cd Sane && docker build .
