
name: Docker images

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        image:
          - "arch"

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: true

      - name: Set up QEMU
        if: "matrix.qemu-arch"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.qemu-arch }}

      - name: Prepare build
        run: |
          sudo apt-get update && sudo apt-get install -qyy debootstrap
          if [[ -n "$matrix.test-image" ]]; then
            git submodule update --remote --init --recursive Pillow
          else
            git submodule update --remote Pillow
          fi
          (cd Pillow && git checkout main)
          sudo chown -R 1001 $(pwd)

      - name: Test Image Build
        if: "matrix.test-image"
        run: |
          cd "${{ matrix.test-image }}"
          make pull || (sudo chmod a+w . && make update && make build BRANCH=main)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ARGS: ${{ matrix.docker-args }}

      - name: Build image
        id: build
        run: |
          cd "${{ matrix.image }}" && sudo chmod a+w . && make update
          if [[ -n "$DOCKER_USERNAME" ]]; then
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && echo "logged_in=true" >> $GITHUB_OUTPUT
          fi
          make build BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ARGS: ${{ matrix.docker-args }}

      - name: Log image size
        run: |
          docker images

      - name: Push image
        if: "steps.build.outputs.logged_in == 'true'
                           && github.event_name == 'push'
                           && github.ref == 'refs/heads/main'"
        run: make push-${{ matrix.image }} BRANCH=main
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Post build
        if: always()
        run: sudo chown -R $(id -u) $(pwd)

  success:
    needs: build
    runs-on: ubuntu-latest
    name: Build successful
    steps:
      - name: Success
        run: echo Build Successful
